# Debugging mode to log more about what's going on
debug: true

# Redis messenger settings
redis:
  host: localhost
  port: 6379
  timeout: 60
  password: password1
# you can also directly set the uri for example like this (directly set values overwrite uri parameter 'though):
# uri: redis://password1@localhost:6379/database?timeout=60s [&database=database]

# Whether or not the plugin should query inventories on other server
# or just move the player to the server with the newest inventory
query-inventories: true

# The name of the group this server is in. Set that to the same value
# on all servers which's data you want to get synced.
server-group: survival

# The name of this server. If you don't want to query inventories then
# this has to be the same as the name in your BungeeCord's config.yml
server-name: server1 # CHANGE THIS!

# Whether or not we should sync the data with all servers in a group
# when a player logs out. Use this if your servers have the tendency
# to not always be online.
sync-with-group-on-logout: true

# Store player data even if the player never joined the server
# This will create a player.dat when the data is synced and most likely
# breaks first join detection of other plugins
store-unknown-players: true

# The amount of seconds we should maximally wait for all servers to
# respond to a query
query-timeout: 5

# Whether or not we should load the data from queries that timed out
# This might run into issues if the server with the most recent data
# is not online at the moment of querying!
apply-timed-out-queries: false

# Should the plugin try to keep maps in sync?
sync-maps: true

# Language settings
lang:
  cant-pickup-exp: "&cDu kannst erst Erfahrung aufsammeln wenn deine Spielerdaten geladen sind!"
  cant-pickup-items: "&cDu kannst erst Items aufsammeln wenn deine Spielerdaten geladen sind!"
  cant-drop-items: "&cDu kannst erst Items droppen wenn deine Spielerdaten geladen sind!"
  cant-move: "&cDu kannst dich erst bewegen wenn deine Spielerdaten geladen sind!"
  wait-for-loading: "&cBitte warte bis deine Spielerdaten geladen sind!"
  cant-load-data: "&cTut uns leid aber der Server konnte nicht deine aktuellen Daten nicht laden.\nKontaktiere die Serverleitung wenn dies öfter passieren sollte!"